import { type AppType } from "next/dist/shared/lib/utils";
import dynamic from "next/dynamic";
import Head from "next/head";

import "../styles/globals.css";
import GUI from "@/components/dom/GUI";

const Scene = dynamic(() => import("@/components/canvas/Scene"), {
  ssr: true,
});

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />

      <Scene />
      <GUI />
    </>
  );
};

export default MyApp;
